config/routes.rb
Rails.application.routes.draw do
  

  root 'pokemons#index'
  resources :pokemons

end

app/models/pokemon.rb
class Pokemon < ActiveRecord::Base
  has_many :entries
  has_many :descriptions
  has_attached_file :sprite,
    :url => "/../app/assets/images/:basename.:extension",  
    :path => ":rails_root/app/assets/images/:basename.:extension"  
  validates_attachment_file_name :sprite, matches: [/svg\Z/, /jpe?g\Z/]


  def select_entry(language)
    self.entries.find_by(language: language)
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def index
    @pokemons = Pokemon.all
  end
  def show
    @pokemon = Pokemon.find(params[:id])
    @language = params[:language] #set default language
  end

end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/pokemons/_link.html.erb
<div id="lang_nav" class="line">
  <h3>
    <% links.each do |link| %>
      <%= link_to image_tag("#{link}.svg", id: "bulba"), pokemon_path(pokemon, language: link) %>
    <% end %>
  </h3>
</div>

app/views/pokemons/index.html.erb
<ul>
  <div class="line">
    <% @pokemons.each do |pokemon| %>
      <div class="item">
        <li><%= link_to image_tag("#{pokemon.number}.svg", id: "icon"), pokemon_path(pokemon, language: "ermahgerd") %></li>
      </div>
    <% end %>
  </div>
</ul>

app/views/pokemons/show.html.erb
<nav>
  <%= render partial: "link", locals: {links: ["ermahgerd", "chef", "pirate", "fudd"], pokemon: params[:id]} %>
</nav>
<main>
  <section>
    <div class="title">
      <h1><%= @pokemon.select_entry(@language).name %></h1>
    </div>
  </section>
  <section>
    <div class="sprite">
      <%= image_tag("#{@pokemon.number}.svg") %>  
    </div>
    <div class="translation">
      <h2><%= @pokemon.select_entry(@language).number %></h2>
      <h2><%= @pokemon.select_entry(@language).select_translation.text %></h2>
    </div>
  </section>
</main>
<div class="back_link">
  <h2><%= link_to "Back to Pokedex", pokemons_path %></h2>
<div>